import Link from "next/link";
import Image from "next/image";
import Head from "next/head";
import styles from "../../styles/Home.module.css";
import { useState, useCallback } from "react";

export async function getServerSideProps() {
  const quotesResponse = await fetch("http://localhost:3000/api/quotes");
  const quotes = await quotesResponse.json();
  return {
    props: {
      quotes,
    },
  };
}

export default function Quotes({ quotes }) {
  const [allQuotes, setAllQuotes] = useState(quotes);
  const [increment, { loading }] = useIncrement();

  const handleIncrement = async (id) => {
    await increment(id);
    const quotesResponse = await fetch("http://localhost:3000/api/quotes");
    const quotes = await quotesResponse.json();
    setAllQuotes(quotes);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Quotes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Chuck Norris Quotes</h1>
        <ul>
          {allQuotes.map((quote) => (
            <li key={quote.id} className={styles.quoteCard}>
              <blockquote>{quote.value}</blockquote>
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "flex-end",
                }}
              >
                <div
                  style={{
                    display: "flex",
                    justifyContent: "flex-start",
                    alignItems: "center",
                  }}
                >
                  <Image src={quote.icon_url} width={25} height={25} /> Uttered{" "}
                  {quote.charlieUtterance} times
                  <button
                    onClick={() => handleIncrement(quote.id)}
                    disabled={loading}
                    className={styles.incrementButton}
                  >
                    +1
                  </button>
                </div>
                <Link href={`/quotes/${quote.id}`}>
                  <a>Go to Quote page</a>
                </Link>
              </div>
            </li>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

function useIncrement() {
  const [data, setData] = useState();
  const [loading, setLoading] = useState(false);
  const mutate = useCallback((id) => {
    setLoading(true);
    return fetch("http://localhost:3000/api/quotes/increment?id=" + id)
      .then((res) => res.json())
      .then((json) => setData(json))
      .catch((error) => console.log(error))
      .finally(() => setLoading(false));
  }, []);

  return [mutate, { data, loading }];
}
